'use client';
import Link from 'next/link';
import { FormEvent, useState } from 'react';

export default function TambahKasir(){
  const [fullName,setFullName]=useState(''); const [email,setEmail]=useState(''); const [password,setPassword]=useState('');
  const [message,setMessage]=useState(''); const [busy,setBusy]=useState(false); const [done,setDone]=useState(false);
  async function submit(e:FormEvent){e.preventDefault();setBusy(true);setMessage('');
    try { const res=await fetch('/api/admin',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({full_name:fullName,email,password})}); const data=await res.json(); if(!res.ok||!data.ok) throw new Error(data.error||'Gagal menambahkan kasir'); setDone(true); }
    catch(e){setMessage(e instanceof Error?e.message:'Gagal menambahkan kasir');} finally{setBusy(false)}
  }
  if(done) return <section className="auth-page"><div className="page-head"><div><div className="eyebrow">Tim toko</div><h1>Kasir berhasil ditambahkan</h1><p className="muted">Akun siap digunakan untuk masuk ke POS.</p></div></div><div className="card auth-card"><div className="success-panel"><span className="success-mark">✓</span><div><strong>{fullName}</strong><p className="muted">{email}</p></div></div><p className="muted">Berikan email dan password ini kepada kasir secara aman. Kasir akan masuk menggunakan akun yang dibuat oleh owner.</p><div className="row-actions"><Link className="btn" href="/karyawan">Kembali ke Karyawan</Link><button className="btn btn-ghost" onClick={()=>{setDone(false);setFullName('');setEmail('');setPassword('')}}>Tambah kasir lagi</button></div></div></section>;
  return <section className="auth-page"><div className="page-head"><div><div className="eyebrow">Tim toko</div><h1>Tambah kasir</h1><p className="muted">Buat akun kasir baru dan langsung hubungkan ke toko Anda.</p></div><Link className="btn btn-ghost" href="/karyawan">← Kembali</Link></div><form className="card auth-card" onSubmit={submit}><div className="form-note"><strong>Akun kasir</strong><span>Hanya owner yang dapat membuat akun baru.</span></div><label>Nama Lengkap<input value={fullName} onChange={e=>setFullName(e.target.value)} maxLength={120} required autoComplete="name" placeholder="Contoh: Budi Santoso"/></label><label>Email Login<input type="email" value={email} onChange={e=>setEmail(e.target.value)} required autoComplete="email" placeholder="kasir@toko.com"/></label><label>Password Awal<input type="password" value={password} onChange={e=>setPassword(e.target.value)} minLength={6} maxLength={72} required autoComplete="new-password" placeholder="Minimal 6 karakter"/></label>{message&&<p role="alert" className="error-text">{message}</p>}<button className="btn" disabled={busy}>{busy?'Membuat akun…':'Buat Akun Kasir'}</button><p className="muted" style={{margin:0,fontSize:12}}>Akun dibuat oleh server menggunakan Supabase Auth; password tidak disimpan di tabel aplikasi.</p></form></section>
}
