'use client';
import Link from 'next/link';
import { FormEvent, useEffect, useMemo, useState } from 'react';

type Product={id:string;name:string;sku:string|null;stock:number|string;minimum_stock:number|string;unit:string};
const fmt=(v:number)=>Number(v).toLocaleString('id-ID');
export default function Page(){
 const [items,setItems]=useState<Product[]>([]); const [q,setQ]=useState(''); const [filter,setFilter]=useState('semua'); const [loading,setLoading]=useState(true); const [error,setError]=useState(''); const [owner,setOwner]=useState(false); const [productId,setProductId]=useState(''); const [movementType,setMovementType]=useState('in'); const [quantity,setQuantity]=useState('1'); const [reason,setReason]=useState(''); const [busy,setBusy]=useState(false); const [message,setMessage]=useState('');
 async function load(){setLoading(true);setError('');try{const r=await fetch('/api/stock',{cache:'no-store'});const j=await r.json();if(!j.ok)throw new Error(j.error||'Gagal mengambil stok');setItems(j.data)}catch(e:unknown){setError(e instanceof Error&&e.message?e.message:'Gagal mengambil stok')}finally{setLoading(false)}}
 useEffect(()=>{load();fetch('/api/admin').then(r=>setOwner(r.ok)).catch(()=>setOwner(false))},[]);
 const filtered=useMemo(()=>items.filter(p=>(filter==='semua'||(filter==='menipis'?Number(p.stock)<=Number(p.minimum_stock):Number(p.stock)>Number(p.minimum_stock)))&&(!q||`${p.name} ${p.sku??''}`.toLowerCase().includes(q.toLowerCase()))),[items,q,filter]);
 const low=items.filter(p=>Number(p.stock)<=Number(p.minimum_stock)).length;
 const selectedProduct=items.find(p=>p.id===productId);
 async function moveStock(e:FormEvent){e.preventDefault();setBusy(true);setMessage('');setError('');try{let qty=Number(quantity); if(movementType==='adjustment'){ if(!selectedProduct)throw new Error('Pilih produk terlebih dahulu'); qty=qty-Number(selectedProduct.stock); if(qty===0){setMessage('Tidak ada perubahan stok.');setBusy(false);return;} } const r=await fetch('/api/stock/movement',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({product_id:productId,quantity:qty,movement_type:movementType,reason})});const j=await r.json();if(!j.ok)throw new Error(j.error||'Gagal memperbarui stok');setMessage('Mutasi stok berhasil disimpan.');setQuantity('1');setReason('');setProductId('');await load()}catch(e:unknown){setError(e instanceof Error&&e.message?e.message:'Gagal memperbarui stok')}finally{setBusy(false)}}
 return <section><div className="page-head"><div><div className="eyebrow">Persediaan</div><h1>Stok</h1><p className="muted">Pantau stok dan catat mutasi secara terkontrol.</p></div><button className="btn btn-ghost" onClick={load} disabled={loading}>↻ Muat Ulang</button></div>
  <div className="grid grid-4"><div className="card"><div className="muted">Total produk</div><div className="metric">{items.length}</div></div><div className="card"><div className="muted">Stok menipis</div><div className="metric">{low}</div></div><div className="card"><div className="muted">Stok kosong</div><div className="metric">{items.filter(p=>Number(p.stock)<=0).length}</div></div><div className="card"><div className="muted">Status</div><div className="metric">Aktif</div></div></div>
  {error&&<div className="card alert-danger">{error}</div>}
  <div className="toolbar page-toolbar"><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Cari produk atau SKU…"/><select value={filter} onChange={e=>setFilter(e.target.value)}><option value="semua">Semua stok</option><option value="menipis">Menipis</option><option value="aman">Aman</option></select></div>

  {owner&&<div className="card stock-movement-card"><div className="section-title"><div><h3>Mutasi stok</h3><p className="muted">Tambah, kurangi, atau sesuaikan stok dengan alasan yang tercatat.</p></div><span className="badge badge-ok">Owner</span></div><form className="stock-movement-form" onSubmit={moveStock}><select value={productId} onChange={e=>setProductId(e.target.value)} required><option value="">Pilih produk…</option>{items.map(p=><option key={p.id} value={p.id}>{p.name} · stok {p.stock} {p.unit}</option>)}</select><select value={movementType} onChange={e=>setMovementType(e.target.value)}><option value="in">Stok masuk (+jumlah)</option><option value="out">Stok keluar (-jumlah)</option><option value="adjustment">Penyesuaian (isi stok akhir)</option></select><input type="number" min={movementType==='adjustment'?'0':'0.001'} step="0.001" value={quantity} onChange={e=>setQuantity(e.target.value)} placeholder={movementType==='adjustment'?'Stok akhir yang benar':'Jumlah'} required/>{movementType==='adjustment'&&selectedProduct&&<p className="muted" style={{margin:0}}>Stok sekarang {selectedProduct.stock} {selectedProduct.unit} → akan jadi {quantity||0} {selectedProduct.unit} (selisih {(Number(quantity)||0)-Number(selectedProduct.stock)>0?'+':''}{(Number(quantity)||0)-Number(selectedProduct.stock)})</p>}<input value={reason} onChange={e=>setReason(e.target.value)} placeholder="Alasan mutasi…" maxLength={255} required/><button className="btn" disabled={busy||!productId}>{busy?'Menyimpan…':'Simpan mutasi'}</button></form>{message&&<p className="muted">{message}</p>}</div>}
  <div className="card table-wrap">{loading?<p className="muted">Memuat stok…</p>:filtered.length===0?<p className="empty">Tidak ada produk yang cocok.</p>:<table className="table"><thead><tr><th>Produk</th><th>SKU</th><th>Stok</th><th>Minimum</th><th>Kondisi</th><th></th></tr></thead><tbody>{filtered.map(p=><tr key={p.id}><td><strong>{p.name}</strong></td><td>{p.sku||'—'}</td><td>{fmt(Number(p.stock))} {p.unit}</td><td>{fmt(Number(p.minimum_stock))} {p.unit}</td><td>{Number(p.stock)<=Number(p.minimum_stock)?<span className="badge badge-warn">Perlu perhatian</span>:<span className="badge badge-ok">Aman</span>}</td><td><Link className="btn btn-ghost btn-sm" href={`/produk/${p.id}`}>Atur</Link></td></tr>)}</tbody></table>}</div>
  <div className="card info-card"><strong>Catatan stok</strong><p className="muted">Perubahan stok dilakukan melalui mutasi agar riwayat stok tetap tercatat dan dapat diaudit. Gunakan halaman produk untuk melihat data dasar produk.</p></div>
 </section>
}
