'use client';
import { FormEvent, useEffect, useMemo, useState } from 'react';
import { createClient } from '@/lib/supabase/browser';
type Customer={id:string;name:string;phone:string|null;address:string|null;notes:string|null;created_at:string};
export default function Page(){const supabase=useMemo(()=>createClient(),[]);const [items,setItems]=useState<Customer[]>([]);const [q,setQ]=useState('');const [name,setName]=useState('');const [phone,setPhone]=useState('');const [address,setAddress]=useState('');const [busy,setBusy]=useState(false);const [msg,setMsg]=useState('');
 async function load(){const {data}=await supabase.from('customers').select('*').order('name');setItems(data??[])} useEffect(()=>{load()},[]);
 async function add(e:FormEvent){e.preventDefault();if(!name.trim())return;setBusy(true);setMsg('');try{const {data:{user}}=await supabase.auth.getUser();if(!user){setMsg('Sesi login tidak ditemukan.');return}const {data:member,error:memberError}=await supabase.from('shop_members').select('shop_id').eq('user_id',user.id).eq('active',true).maybeSingle();if(memberError||!member){setMsg('Toko aktif tidak ditemukan.');return}const {error}=await supabase.from('customers').insert({shop_id:member.shop_id,name:name.trim(),phone:phone.trim()||null,address:address.trim()||null});if(error)setMsg(error.message);else{setName('');setPhone('');setAddress('');setMsg('Pelanggan ditambahkan.');await load()}}finally{setBusy(false)}}
 const filtered=items.filter(c=>`${c.name} ${c.phone??''} ${c.address??''}`.toLowerCase().includes(q.toLowerCase()));
 return <section><div className="page-head"><div><div className="eyebrow">Relasi pelanggan</div><h1>Pelanggan</h1><p className="muted">Simpan kontak pelanggan agar transaksi lebih mudah dilacak.</p></div></div><div className="grid grid-2"><div className="card"><h3>Tambah pelanggan</h3><form className="form-grid" onSubmit={add}><label>Nama<input value={name} onChange={e=>setName(e.target.value)} required/></label><label>No. HP<input value={phone} onChange={e=>setPhone(e.target.value)} inputMode="tel"/></label><label>Alamat<input value={address} onChange={e=>setAddress(e.target.value)}/></label>{msg&&<p className="muted">{msg}</p>}<button className="btn" disabled={busy}>{busy?'Menyimpan…':'Simpan pelanggan'}</button></form></div><div className="card"><div className="section-title"><div><h3>Daftar pelanggan</h3><p className="muted">{items.length} pelanggan tersimpan.</p></div></div><div className="toolbar"><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Cari pelanggan…"/></div>{filtered.length===0?<p className="empty">Belum ada pelanggan.</p>:<div className="customer-list">{filtered.map(c=><div className="customer-row" key={c.id}><div><strong>{c.name}</strong><span>{c.phone||'No. HP belum diisi'}{c.address?` · ${c.address}`:''}</span></div></div>)}</div>}</div></div></section>}
